[server]
maxUploadSize = 200
timeout = 300

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif" 